#!/usr/bin/env bash
BASEDIR=$(dirname $0)
cd $BASEDIR

ln -s ${PWD}/.bashrc ~/.bashrc
ln -s ${PWD}/.bash_aliases ~/.bash_aliases
ln -s ${PWD}/.vimrc ~/.vimrc
ln -s ${PWD}/.vim ~/.vim
ln -s ${PWD}/.tmux.conf ~/.tmux.conf
ln -s ${PWD}/.gitconfig ~/.gitconfig
ln -s ${PWD}/bin ~/bin
