#!/usr/bin/env bash
BASEDIR=$(dirname $0)
cd $BASEDIR

ln -sf ${PWD}/.bashrc ~/.bashrc
ln -sf ${PWD}/.bash_aliases ~/.bash_aliases
ln -sf ${PWD}/.vimrc ~/.vimrc
ln -sf ${PWD}/.vim ~/.vim
ln -sf ${PWD}/.gitconfig ~/.gitconfig
ln -sf ${PWD}/bin ~/bin
